import ThemeRegistry from "@/config/ThemeRegistry";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@/styles/global.scss";
const opensans = Open_Sans({
  weight: ["400", "300", "500", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        <ThemeRegistry options={{ key: "mui" }}>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
